version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/nodejs-docker-app
hooks:
  stop.sh:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu

